from weasyprint import HTML
import os

html_content = """
<!DOCTYPE html>
<html>
<head>
    <title>Invoice</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .invoice-box {
            width: 100%;
            border: 1px solid #eee;
            padding: 20px;
            margin-top: 50px;
        }
    </style>
</head>
<body>
    <div class="invoice-box">
        <h1>Invoice</h1>
        <p>This is a sample invoice generated by WeasyPrint.</p>
    </div>
</body>
</html>
"""

output_path = "/app/invoice.pdf"

HTML(string=html_content).write_pdf(output_path)

if os.path.exists(output_path):
    print(f"Invoice generated and saved as {output_path}")
else:
    print("Failed to generate the invoice.")
